[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python -m uvicorn web_app:app --host 0.0.0.0 --port ${PORT:-8000}"

